# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-commerce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-commerce
pod 'Firebase'

pod 'Firebase/Auth'

pod 'Firebase/Firestore'

pod 'Firebase/Storage'


pod 'Firebase/Analytics'

pod 'Firebase/Messaging'

pod 'Firebase/Crashlytics'




pod 'SDWebImage', '~> 5.0'
pod 'Stripe','~> 19.3.0'
pod 'JJFloatingActionButton'

pod "JDropDownAlert"

pod 'SVProgressHUD'

pod 'PopupDialog', '~> 1.1'

pod 'SwiftyAttributes'


pod 'ActiveLabel'

pod 'OEMentions'

pod 'lottie-ios'
pod 'RevealingSplashView'

pod 'TweeTextField'

pod "CreditCardForm"

  target 'E-commerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-commerceUITests' do
    # Pods for testing
  end

end
